Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputShape:
- null
- 16
OutputDir: /home/abdel/IRIS_HEP/javiers_example/hls_output/
ProjectName: myproject
PytorchModel: !!python/object:__main__.three_layer_model_batnorm_masked
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - fc1
      - !!python/object:torch.nn.modules.linear.Linear

  ...
Stamp: D270715d
XilinxPart: xcku115-flvb2104-2-i
