Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
OutputDir: /home/abdel/IRIS_HEP/GNN_hls_layers/hls_output
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
edge_dim: 4
n_edges: 148
n_nodes: 112
node_dim: 3
